FROM node:10

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

ENV API_URL=http://localhost:8000
EXPOSE 5000
CMD npm start
