FROM node:10-alpine as build-stage

WORKDIR /usr/src/app

COPY . .

RUN npm install --production && \
    adduser -D app && \
    chown -R app .

ENV API_URL=http://localhost:8000
EXPOSE 5000

USER app

CMD ["npm", "start"]
