FROM node:10-alpine

WORKDIR /usr/src/app

COPY . .

RUN npm install --production && \
    adduser -D app && \
    chown -R app .

ENV FRONT_URL=http://localhost:5000
EXPOSE 8000

USER app

CMD ["npm", "start"]
