version: '3.5' 

services: 

    backend:
      image: backend
      build: ../../backend-example-docker/
      ports:
        - '8000:8000'
      environment:
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
      depends_on:
        - redis

    frontend:
      image: frontend
      build: ../../frontend-example-docker/
      ports:
        - '5000:5000'
      environment:
        - API_URL=http://localhost:8000

    redis:
      image: redis
      container_name: cache
      expose:
        - 6379