FROM ubuntu:16.04

WORKDIR /app
COPY package*.json ./

RUN apt-get update && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash && \
    apt-get install -y nodejs && \
    apt-get purge -y --auto-remove curl && \ 
    rm -rf /var/lib/apt/lists/* && \
    npm install

COPY . .

ENV FRONT_URL=http://localhost:5000
EXPOSE 8000

CMD ["npm", "start"]
