version: '3.5' 

services: 
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: database

  backend:
    image: backend
    build: ../../backend-example-docker/
    ports:
      - '8000:8000'
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_NAME=postgres
      - DB_HOST=database
    depends_on:
      - redis
      - db

  frontend:
    image: frontend
    build: ../../frontend-example-docker/
    ports:
      - '5000:5000'
    environment:
      - API_URL=http://localhost:8000

  redis:
    image: redis
    container_name: cache
    ports:
      - '6379:6379'
